#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Qurany.Resource", IsApplication=true)]

namespace Qurany
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int androidcolors = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070010
			public const int black = 2131165200;
			
			// aapt resource value: 0x7f070000
			public const int black_overlay = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int blue = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int customeblue = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int darkblue = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int darkgreen = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int darkorange = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int darkpurple = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int darkred = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int green = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int lowDarkfont = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int orange = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int purple = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int red = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int white = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int whiteback = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int whitebackground = 2131165199;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgroundW = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int color_cursor = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edittext_rounded = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ico = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int layout1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int r_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int s_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int t_launcher = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int top = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0011
			public const int ImageDown = 2131361809;
			
			// aapt resource value: 0x7f0a0016
			public const int ImageDownS = 2131361814;
			
			// aapt resource value: 0x7f0a0013
			public const int ImageUp = 2131361811;
			
			// aapt resource value: 0x7f0a0018
			public const int ImageUpS = 2131361816;
			
			// aapt resource value: 0x7f0a0005
			public const int ScrollViewID = 2131361797;
			
			// aapt resource value: 0x7f0a000d
			public const int Textv2 = 2131361805;
			
			// aapt resource value: 0x7f0a0021
			public const int adView1 = 2131361825;
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a0023
			public const int aya = 2131361827;
			
			// aapt resource value: 0x7f0a0004
			public const int button1next = 2131361796;
			
			// aapt resource value: 0x7f0a001b
			public const int checkBox1 = 2131361819;
			
			// aapt resource value: 0x7f0a000a
			public const int editText1 = 2131361802;
			
			// aapt resource value: 0x7f0a0003
			public const int editTextSearch = 2131361795;
			
			// aapt resource value: 0x7f0a0024
			public const int help = 2131361828;
			
			// aapt resource value: 0x7f0a0015
			public const int linearLayou8 = 2131361813;
			
			// aapt resource value: 0x7f0a0006
			public const int linearLayout1 = 2131361798;
			
			// aapt resource value: 0x7f0a0019
			public const int linearLayout2 = 2131361817;
			
			// aapt resource value: 0x7f0a0020
			public const int linearLayout3 = 2131361824;
			
			// aapt resource value: 0x7f0a000e
			public const int linearLayout4 = 2131361806;
			
			// aapt resource value: 0x7f0a001a
			public const int linearLayout5 = 2131361818;
			
			// aapt resource value: 0x7f0a0010
			public const int linearLayout7 = 2131361808;
			
			// aapt resource value: 0x7f0a000c
			public const int listView1 = 2131361804;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a0012
			public const int seekBarcounT = 2131361810;
			
			// aapt resource value: 0x7f0a0017
			public const int seekBartimeS = 2131361815;
			
			// aapt resource value: 0x7f0a0022
			public const int share = 2131361826;
			
			// aapt resource value: 0x7f0a000b
			public const int textView1 = 2131361803;
			
			// aapt resource value: 0x7f0a001c
			public const int textView2 = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int textView3 = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int textView4 = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int textView5 = 2131361823;
			
			// aapt resource value: 0x7f0a0009
			public const int textViewAfter = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int textViewAya = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int textViewBefor = 2131361799;
			
			// aapt resource value: 0x7f0a0014
			public const int textViewStrat = 2131361812;
			
			// aapt resource value: 0x7f0a000f
			public const int textViewcount = 2131361807;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int aya = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int mylist = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int setting1 = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu1 = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int ApplicationName = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Banner_Ads = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int Hello = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int accept = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int action_deep_link = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int create_calendar_message = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int create_calendar_title = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int decline = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int store_picture_message = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int store_picture_title = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_AppInvite_Preview = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_AppInvite_Preview_Base = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int Theme_IAPTheme = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
